#!/bin/bash

while [ -n "$1" ]
do
case "$1" in
-i) id=$2;;
-f) format=$2;;
esac
shift
done
# shellcheck disable=SC2164
if [ -d "/transcoding/$id/480" ]; then
  rm -r /transcoding/"$id"/480/*
else
  mkdir /transcoding/"$id"/480
fi

if [ -d "/transcoding/$id/720" ]; then
  rm -r /transcoding/"$id"/720/*
else
  mkdir /transcoding/"$id"/720
fi

if [ -d "/transcoding/$id/1080" ]; then
  rm -r /transcoding/"$id"/1080/*
else
  mkdir /transcoding/"$id"/1080
fi

rm -r /transcoding/"$id"/480.m3u8
rm -r /transcoding/"$id"/720.m3u8
rm -r /transcoding/"$id"/1080.m3u8

cd /transcoding/"$id"
ffmpeg -y -i "video-${id}.${format}" \
-filter_complex \
"[0:v]split=3[v1][v2][v3]; \
 [v1]scale=854:480:flags=lanczos[v480]; \
 [v2]scale=1280:720:flags=lanczos[v720]; \
 [v3]scale=1920:1080:flags=lanczos[v1080]" \
-map "[v480]" -map 0:a \
  -c:v h264_nvenc -preset p4 -profile:v main -rc:v vbr -cq 24 -b:v 2000k -maxrate 2500k -bufsize 5000k \
  -bf 0 -rc-lookahead 0 -pix_fmt yuv420p -c:a aac -ar 48000 \
  -hls_time 10 -hls_playlist_type vod -hls_list_size 0 -reset_timestamps 1 \
  -hls_base_url "https://proxy.animeon.ru/video/$id/480/" \
  -hls_segment_filename "480/${id}-%05d.ts" 480.m3u8 \
-map "[v720]" -map 0:a \
  -c:v h264_nvenc -preset p4 -profile:v main -rc:v vbr -cq 23 -b:v 3500k -maxrate 4000k -bufsize 8000k \
  -bf 0 -rc-lookahead 0 -pix_fmt yuv420p -c:a aac -ar 48000 \
  -hls_time 10 -hls_playlist_type vod -hls_list_size 0 -reset_timestamps 1 \
  -hls_base_url "https://proxy.animeon.ru/video/$id/720/" \
  -hls_segment_filename "720/${id}-%05d.ts" 720.m3u8 \
-map "[v1080]" -map 0:a \
  -c:v h264_nvenc -preset p4 -profile:v high -rc:v vbr -cq 22 -b:v 6000k -maxrate 7000k -bufsize 12000k \
  -bf 0 -rc-lookahead 0 -pix_fmt yuv420p -c:a aac -ar 48000 \
  -hls_time 10 -hls_playlist_type vod -hls_list_size 0 -reset_timestamps 1 \
  -hls_base_url "https://proxy.animeon.ru/video/$id/1080/" \
  -hls_segment_filename "1080/${id}-%05d.ts" 1080.m3u8
# shellcheck disable=SC2103
cd ..
